routes/web.php
<?php
# Backend Controllers
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\BackendAdminController;
use App\Http\Controllers\Backend\BackendNotificationsController;
use App\Http\Controllers\Backend\BackendHelperController;
use App\Http\Controllers\Backend\BackendTestController;
use App\Http\Controllers\Backend\BackendProfileController;
use App\Http\Controllers\Backend\BackendArticleController;
use App\Http\Controllers\Backend\BackendArticleCommentController;
use App\Http\Controllers\Backend\BackendSiteMapController;
use App\Http\Controllers\Backend\BackendSettingController;
use App\Http\Controllers\Backend\BackendContactController;
use App\Http\Controllers\Backend\BackendCategoryController;
use App\Http\Controllers\Backend\BackendRedirectionController;
use App\Http\Controllers\Backend\BackendUserController;
use App\Http\Controllers\Backend\BackendTrafficsController;
use App\Http\Controllers\Backend\BackendPageController;
use App\Http\Controllers\Backend\BackendMenuController;
use App\Http\Controllers\Backend\BackendMenuLinkController;
use App\Http\Controllers\Backend\BackendFileController;
use App\Http\Controllers\Backend\BackendFaqController;
use App\Http\Controllers\Backend\BackendContactReplyController;
use App\Http\Controllers\Backend\BackendAnnouncementController;
use App\Http\Controllers\Backend\BackendPermissionController;
use App\Http\Controllers\Backend\BackendUserPermissionController;
use App\Http\Controllers\Backend\BackendUserRoleController;
use App\Http\Controllers\Backend\BackendRoleController;
use App\Http\Controllers\Backend\BackendTagController;
use App\Http\Controllers\Backend\BackendPluginController;


# Frontend Controllers
use App\Http\Controllers\FrontController;
use App\Http\Controllers\FrontendProfileController;

Auth::routes();

Route::get('rooms', 'ChatController@UserRooms');
Route::get('chat/{room}', 'ChatController@GetChat');
Route::post('save-message', 'ChatController@SaveMessage');

Route::get('public-chat', 'ChatController@PublicChat');
Route::get('chat-list', 'ChatController@OtherUsers');
// Route::post('chat-list', [ChatController::class, 'OtherUsers']);
Route::get('create-private-room/{user}', 'ChatController@NewPrivateRoom');



Route::get('/', [FrontController::class, 'index'])->name('home');
Route::get('/index2', function () {
    return view('front.index2');
})->name('index2');



Route::prefix('dashboard')->middleware(['auth', 'ActiveAccount', 'verified'])->name('user.')->group(function () {
    Route::get('/', [FrontendProfileController::class, 'dashboard'])->name('dashboard');
    Route::get('/support', [FrontendProfileController::class, 'support'])->name('support');
    Route::get('/support/create-ticket', [FrontendProfileController::class, 'create_ticket'])->name('create-ticket');
    Route::post('/support/create-ticket', [FrontendProfileController::class, 'store_ticket'])->name('store-ticket');
    Route::get('/support/{ticket}', [FrontendProfileController::class, 'ticket'])->name('ticket');
    Route::post('/support/{ticket}/reply', [FrontendProfileController::class, 'reply_ticket'])->name('reply-ticket');
    Route::get('/notifications', [FrontendProfileController::class, 'notifications'])->name('notifications');
    Route::prefix('profile')->name('profile.')->group(function () {
        Route::get('/settings', [FrontendProfileController::class, 'profile_edit'])->name('edit');
        Route::put('/update', [FrontendProfileController::class, 'profile_update'])->name('update');
        Route::put('/update-password', [FrontendProfileController::class, 'profile_update_password'])->name('update-password');
        Route::put('/update-email', [FrontendProfileController::class, 'profile_update_email'])->name('update-email');
    });
});



#Route::get('/test',[BackendTestController::class,'test']);

Route::prefix('admin')->middleware(['auth', 'ActiveAccount'])->name('admin.')->group(function () {

    Route::get('/', [BackendAdminController::class, 'index'])->name('index');
    Route::middleware('auth')->group(function () {
        Route::resource('announcements', BackendAnnouncementController::class);
        Route::resource('files', BackendFileController::class);
        Route::post('contacts/resolve', [BackendContactController::class, 'resolve'])->name('contacts.resolve');
        Route::resource('contacts', BackendContactController::class);
        Route::resource('menus', BackendMenuController::class);
        Route::get('users/{user}/access', [BackendUserController::class, 'access'])->name('users.access');
        Route::resource('users', BackendUserController::class);
        Route::resource('roles', BackendRoleController::class);
        Route::get('user-roles/{user}', [BackendUserRoleController::class, 'index'])->name('users.roles.index');
        Route::put('user-roles/{user}', [BackendUserRoleController::class, 'update'])->name('users.roles.update');
        Route::resource('articles', BackendArticleController::class);
        Route::post('article-comments/change_status', [BackendArticleCommentController::class, 'change_status'])->name('article-comments.change_status');
        Route::resource('article-comments', BackendArticleCommentController::class);
        Route::resource('pages', BackendPageController::class);
        Route::resource('tags', BackendTagController::class);
        Route::resource('contact-replies', BackendContactReplyController::class);
        Route::post('faqs/order', [BackendFaqController::class, 'order'])->name('faqs.order');
        Route::resource('faqs', BackendFaqController::class);
        Route::post('menu-links/get-type', [BackendMenuLinkController::class, 'getType'])->name('menu-links.get-type');
        Route::post('menu-links/order', [BackendMenuLinkController::class, 'order'])->name('menu-links.order');
        Route::resource('menu-links', BackendMenuLinkController::class);
        Route::resource('categories', BackendCategoryController::class);
        Route::resource('redirections', BackendRedirectionController::class);
        Route::get('traffics', [BackendTrafficsController::class, 'index'])->name('traffics.index');
        Route::get('traffics/logs', [BackendTrafficsController::class, 'logs'])->name('traffics.logs');
        Route::get('error-reports', [BackendTrafficsController::class, 'error_reports'])->name('traffics.error-reports');
        Route::get('error-reports/{report}', [BackendTrafficsController::class, 'error_report'])->name('traffics.error-report');

        Route::prefix('settings')->name('settings.')->group(function () {
            Route::get('/', [BackendSettingController::class, 'index'])->name('index');
            Route::put('/update', [BackendSettingController::class, 'update'])->name('update');
        });
    });



    Route::prefix('upload')->name('upload.')->group(function () {
        Route::post('/image', [BackendHelperController::class, 'upload_image'])->name('image');
        Route::post('/file', [BackendHelperController::class, 'upload_file'])->name('file');
        Route::post('/remove-file', [BackendHelperController::class, 'remove_files'])->name('remove-file');
    });

    Route::prefix('plugins')->name('plugins.')->group(function () {
        Route::get('/', [BackendPluginController::class, 'index'])->name('index');
        Route::get('/create', [BackendPluginController::class, 'create'])->name('create');
        Route::post('/create', [BackendPluginController::class, 'store'])->name('store');
        Route::post('/{plugin}/activate', [BackendPluginController::class, 'activate'])->name('activate');
        Route::post('/{plugin}/deactivate', [BackendPluginController::class, 'deactivate'])->name('deactivate');
        Route::post('/{plugin}/delete', [BackendPluginController::class, 'delete'])->name('delete');
    });

    Route::prefix('profile')->name('profile.')->group(function () {
        Route::get('/', [BackendProfileController::class, 'index'])->name('index');
        Route::get('/edit', [BackendProfileController::class, 'edit'])->name('edit');
        Route::put('/update', [BackendProfileController::class, 'update'])->name('update');
        Route::put('/update-password', [BackendProfileController::class, 'update_password'])->name('update-password');
        Route::put('/update-email', [BackendProfileController::class, 'update_email'])->name('update-email');
    });

    Route::prefix('notifications')->name('notifications.')->group(function () {
        Route::get('/', [BackendNotificationsController::class, 'index'])->name('index');
        Route::get('/ajax', [BackendNotificationsController::class, 'ajax'])->name('ajax');
        Route::post('/see', [BackendNotificationsController::class, 'see'])->name('see');
        Route::get('/create', [BackendNotificationsController::class, 'create'])->name('create');
        Route::post('/create', [BackendNotificationsController::class, 'store'])->name('store');
    });

});

Route::get('/login/google/redirect', [LoginController::class, 'redirect_google']);
Route::get('/login/google/callback', [LoginController::class, 'callback_google']);
Route::get('/login/facebook/redirect', [LoginController::class, 'redirect_facebook']);
Route::get('/login/facebook/callback', [LoginController::class, 'callback_facebook']);


Route::get('blocked', [BackendHelperController::class, 'blocked_user'])->name('blocked');
Route::get('robots.txt', [BackendHelperController::class, 'robots']);
Route::get('manifest.json', [BackendHelperController::class, 'manifest'])->name('manifest');
Route::get('sitemap.xml', [BackendSiteMapController::class, 'sitemap']);
Route::get('sitemaps/links', [BackendSiteMapController::class, 'custom_links']);
Route::get('sitemaps/{name}/{page}/sitemap.xml', [BackendSiteMapController::class, 'viewer']);


Route::view('contact', 'front.pages.contact')->name('contact');
Route::get('page/{page}', [FrontController::class, 'page'])->name('page.show');

resources/views/admin/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="col-12 p-3 row">
        @can('users-read')
            <div class="col-12 col-sm-6 col-lg-4 col-xl-3 col-xxl-2 px-2 my-2">
                <div class="col-12 px-0 py-1 d-flex main-box-wedit">
                    <div style="width: 65px;" class="p-2">
                        <div class="col-12 px-0 text-center d-flex align-items-center justify-content-center"
                            style="background: #0194fe;color: #fff;border-radius: 50%;width: 55px;height:55px">
                            <span class="fal fa-users font-5"></span>
                        </div>
                    </div>
                    <div style="width: calc(100% - 80px)" class="px-2 py-2">
                        <a class="font-1" href="{{ route('admin.users.index') }}" style="color: #212529">
                            المستخدمين
                            <h6 class="font-3">{{ \App\Models\User::count() }}</h6>
                        </a>
                    </div>
                </div>
            </div>
        @endcan
        <div class="col-12 col-sm-6 col-lg-4 col-xl-3 col-xxl-2 px-2 my-2">
            <div class="col-12 px-0 py-1 d-flex main-box-wedit">
                <div style="width: 65px;" class="p-2">
                    <div class="col-12 px-0 text-center d-flex align-items-center justify-content-center"
                        style="background: #0194fe;color: #fff; border-radius: 50%;width: 55px;height:55px">
                        <span class="fal fa-bells font-5"></span>
                    </div>
                </div>
                <div style="width: calc(100% - 80px)" class="px-2 py-2">
                    <a class="font-1" href="{{ route('admin.notifications.index') }}" style="color: #212529">
                        الإشعارات
                        <h6 class="font-3">{{ auth()->user()->unreadNotifications->count() }}</h6>
                    </a>
                </div>
            </div>
        </div>
        @can('articles-read')
            <div class="col-12 col-sm-6 col-lg-4 col-xl-3 col-xxl-2 px-2 my-2">
                <div class="col-12 px-0 py-1 d-flex main-box-wedit">
                    <div style="width: 65px;" class="p-2">
                        <div class="col-12 px-0 text-center d-flex align-items-center justify-content-center"
                            style="background: #0194fe;color: #fff; border-radius: 50%;width: 55px;height:55px">
                            <span class="fal fa-books font-5"></span>
                        </div>
                    </div>
                    <div style="width: calc(100% - 80px)" class="px-2 py-2">
                        <a class="font-1" href="{{ route('admin.articles.index') }}" style="color: #212529;">
                            المقالات
                            <h6 class="font-3">{{ \App\Models\Article::count() }}</h6>
                        </a>
                    </div>
                </div>
            </div>
        @endcan
        @can('categories-read')
            <div class="col-12 col-sm-6 col-lg-4 col-xl-3 col-xxl-2 px-2 my-2">
                <div class="col-12 px-0 py-1 d-flex main-box-wedit">
                    <div style="width: 65px;" class="p-2">
                        <div class="col-12 px-0 text-center d-flex align-items-center justify-content-center"
                            style="background: #0194fe;color: #fff; border-radius: 50%;width: 55px;height:55px">
                            <span class="fal fa-tag font-5"></span>
                        </div>
                    </div>
                    <div style="width: calc(100% - 80px)" class="px-2 py-2">
                        <a class="font-1" href="{{ route('admin.categories.index') }}" style="color: #212529;">
                            الأقسام
                            <h6 class="font-3">{{ \App\Models\Category::count() }}</h6>
                        </a>
                    </div>
                </div>
            </div>
        @endcan
        @can('hub-files-read')
            <div class="col-12 col-sm-6 col-lg-4 col-xl-3 col-xxl-2 px-2 my-2">
                <div class="col-12 px-0 py-1 d-flex main-box-wedit">
                    <div style="width: 65px;" class="p-2">
                        <div class="col-12 px-0 text-center d-flex align-items-center justify-content-center"
                            style="background: #0194fe;color: #fff; border-radius: 50%;width: 55px;height:55px">
                            <span class="fal fa-file font-5"></span>
                        </div>
                    </div>
                    <div style="width: calc(100% - 80px)" class="px-2 py-2">
                        <a class="font-1" href="{{ route('admin.files.index') }}" style="color: #212529;">
                            الملفات
                            <h6 class="font-3">{{ \App\Models\HubFile::count() }}</h6>
                        </a>
                    </div>
                </div>
            </div>
        @endcan
        @can('menus-read')
            <div class="col-12 col-sm-6 col-lg-4 col-xl-3 col-xxl-2 px-2 my-2">
                <div class="col-12 px-0 py-1 d-flex main-box-wedit">
                    <div style="width: 65px;" class="p-2">
                        <div class="col-12 px-0 text-center d-flex align-items-center justify-content-center"
                            style="background: #0194fe;color: #fff; border-radius: 50%;width: 55px;height:55px">
                            <span class="fal fa-list font-5"></span>
                        </div>
                    </div>
                    <div style="width: calc(100% - 80px)" class="px-2 py-2">
                        <a class="font-1" href="{{ route('admin.menus.index') }}" style="color: #212529;">
                            القوائم
                            <h6 class="font-3">{{ \App\Models\Menu::count() }}</h6>
                        </a>
                    </div>
                </div>
            </div>
        @endcan
        @can('pages-read')
            <div class="col-12 col-sm-6 col-lg-4 col-xl-3 col-xxl-2 px-2 my-2">
                <div class="col-12 px-0 py-1 d-flex main-box-wedit">
                    <div style="width: 65px;" class="p-2">
                        <div class="col-12 px-0 text-center d-flex align-items-center justify-content-center"
                            style="background: #0194fe;color: #fff; border-radius: 50%;width: 55px;height:55px">
                            <span class="fal fa-file-invoice font-5"></span>
                        </div>
                    </div>
                    <div style="width: calc(100% - 80px)" class="px-2 py-2">
                        <a class="font-1" href="{{ route('admin.pages.index') }}" style="color: #212529;">
                            الصفحات
                            <h6 class="font-3">{{ \App\Models\Page::count() }}</h6>
                        </a>
                    </div>
                </div>
            </div>
        @endcan
        @can('contacts-read')
            <div class="col-12 col-sm-6 col-lg-4 col-xl-3 col-xxl-2 px-2 my-2">
                <div class="col-12 px-0 py-1 d-flex main-box-wedit">
                    <div style="width: 65px;" class="p-2">
                        <div class="col-12 px-0 text-center d-flex align-items-center justify-content-center"
                            style="background: #0194fe;color: #fff; border-radius: 50%;width: 55px;height:55px">
                            <span class="fal fa-phone font-5"></span>
                        </div>
                    </div>
                    <div style="width: calc(100% - 80px)" class="px-2 py-2">
                        <a class="font-1" href="{{ route('admin.contacts.index') }}" style="color: #212529;">
                            التواصل
                            <h6 class="font-3">{{ \App\Models\Contact::count() }}</h6>
                        </a>
                    </div>
                </div>
            </div>
        @endcan
        @can('announcements-read')
            <div class="col-12 col-sm-6 col-lg-4 col-xl-3 col-xxl-2 px-2 my-2">
                <div class="col-12 px-0 py-1 d-flex main-box-wedit">
                    <div style="width: 65px;" class="p-2">
                        <div class="col-12 px-0 text-center d-flex align-items-center justify-content-center"
                            style="background: #0194fe;color: #fff; border-radius: 50%;width: 55px;height:55px">
                            <span class="fal fa-bullhorn font-5"></span>
                        </div>
                    </div>
                    <div style="width: calc(100% - 80px)" class="px-2 py-2">
                        <a class="font-1" href="{{ route('admin.announcements.index') }}" style="color: #212529;">
                            الإعلانات
                            <h6 class="font-3">{{ \App\Models\Announcement::count() }}</h6>
                        </a>
                    </div>
                </div>
            </div>
        @endcan

        <div class="col-12 px-2 py-2">
            <div style="height: 4px ;background: rgb(118 169 169);border-radius: 7px;transition: width .5s ease-in-out;width: 0%;"
                id="home-dashboard-divider"></div>
        </div>
        <livewire:dashboard-statistics />
    </div>
@endsection

resources/views/admin/publicChat.blade.php
@extends('layouts.app')

@push('style')
    <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/AdminLTE.min.css') }}" rel="stylesheet">
    <style media="screen">
        .online {
            color: #32CD32;
        }

        .ffside {
            height: 100%;
            position: fixed;
            z-index: 1;
            top: 0;
            right: 0;
            width: 18em;
            overflow-x: hidden;
            padding-top: 50px;
        }

        .chat_box {
            width: 260px;
            padding: 5px;
            position: fixed;
            bottom: 0px;
        }
    </style>
@endpush

@section('content')
    <public-component></public-component>
@endsection

resources/views/admin/roomChat.blade.php
@extends('layouts.app')

@push('style')
    <link href="{{ asset('css/oneChat.css') }}" rel="stylesheet">
@endpush
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (isset($messages) && isset($room))
                    <div class="card">
                        <chat-component :messages="{{ $messages }}" :room="{{ $room }}"></chat-component>
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection